<a href="https://colab.research.google.com/github/cri10dm-4/DSA-5620/blob/main/ICP3/ICP3_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# a.

In [ ]:
# Using NumPy create random vector of size 15 having only Integers in the range 1-20.
a = np.random.randint(1, 20, 15)
print("Array:\n", a)

# 1. Reshape the array to 3 by 5
a_reshaped = a.reshape(3, 5)
print("Array:\n", a_reshaped)

# 2. Print array shape.
print("Shape:\n", a_reshaped.shape)

# 3. Replace the max in each row by 0
for i in range(a_reshaped.shape[0]):
    row_max_index = a_reshaped[i].argmax()
    a_reshaped[i, row_max_index] = 0

print("Modified Array:\n", a_reshaped)

Array:
 [17 13  1 16 10  4 11 10  6 19 13  6  3 16 18]
Array:
 [[17 13  1 16 10]
 [ 4 11 10  6 19]
 [13  6  3 16 18]]
Shape:
 (3, 5)
Modified Array:
 [[ 0 13  1 16 10]
 [ 4 11 10  6  0]
 [13  6  3 16  0]]


# b.

In [ ]:
# Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data type of the array.
b = np.random.randint(0, 100, size=(4, 3), dtype=np.int32)
print("Array:\n", b)
print("Shape:\n", b.shape)
print("Type:\n", type(b))
print("Data type:\n", b.dtype)

Array:
 [[20 99 42]
 [ 3 32  0]
 [78 54  4]
 [70 17  6]]
Shape:
 (4, 3)
Type:
 <class 'numpy.ndarray'>
Data type:
 int32


# c.

In [ ]:
# Write a program to compute the eigenvalues and right eigenvectors of a given square array given below:
# [[ 3 -2]
# [ 1 0]]
c = np.array([[3, -2],
              [1,  0]])
eigenvalues, eigenvectors = np.linalg.eig(c)
print("Array:\n", c)
print("Eigenvalues:\n", eigenvalues)
print("Right Eigenvectors:\n", eigenvectors)

Array:
 [[ 3 -2]
 [ 1  0]]
Eigenvalues:
 [2. 1.]
Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


# d.

In [ ]:
# Compute the sum of the diagonal element of a given array.
# [[0 1 2]
# [3 4 5]]
d = np.array([[0, 1, 2], [3, 4, 5]])
print("Array:\n", d)
diag_sum = np.trace(d)
print("Sum of diagonal elements:\n", diag_sum)

Array:
 [[0 1 2]
 [3 4 5]]
Sum of diagonal elements:
 4


# e.

In [ ]:
# Write a NumPy program to create a new shape to an array without changing its data.
# Reshape 3x2:
# [[1 2]
# [3 4]
# [5 6]]
# Reshape 2x3: [[1 2 3]
# [4 5 6]]

e = np.array([[1, 2], [3, 4], [5, 6]])
print("Array:\n", e)
e_reshaped = e.reshape(2, 3)
print("Reshaped 2x3:\n", e_reshaped)

Array:
 [[1 2]
 [3 4]
 [5 6]]
Reshaped 2x3:
 [[1 2 3]
 [4 5 6]]
